[tool.poetry]
name = "stock-bot"
version = "0.1.0"
description = "stock"
authors = ["Hoando."]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
